### ISSUE TITLE
Bug - Tag problem

### ISSUE THREAD

**Issue by mysth** [wexample/wex#8] opened 2018-07-15 09:51 UTC
Sometimes the tag is not correctly set and can give results like those :

```
lionel-Predator-GX-792:contests (master*) # wex server/start
[#########################......] (80%) > Init services       roxy       
fatal: aucun nom trouvé, impossible de décrire quoi que ce soit.
fatal: aucun nom trouvé, impossible de décrire quoi que ce soit.


[###############################] (100%) > Done !       
fatal: aucun nom trouvé, impossible de décrire quoi que ce soit.
fatal: aucun nom trouvé, impossible de décrire quoi que ce soit.
no crontab for root

Creating network "tmp_default" with the default driver
Creating network "tmp_wex_net" with driver "bridge"
ERROR: no such image: wexample/php7:: invalid reference format


lionel-Predator-GX-792:contests (master*) # 
```

So we have to put ourselves in the scripts project folder and type `git tag latest` to make it work.

**Comment by weeger** [comment] 2019-09-09 08:13
*Sometimes* is not really descriptive..

Unable to reproduce, but may be solved by the new version management : we don't use tags anymore to define wex scripts version.

Closing but please comment or update with more information if not solved by v3.

**Closed by weeger** 2019-09-09 08:13 UTC
